project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - src/**/*.qmd

website:
  title: "Accumultor Series"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: src/index.qmd
        text: Articles
